jobs:
  include:
    - stage: build
      if: tag IS present
      script: ./scripts/build-tag.sh

    - stage: build
      if: branch = main AND tag IS blank
      script: ./scripts/build-branch.sh

before_script:
  - |
    if [ "$TRAVIS_TAG" != "" ]; then
      echo "Tag build detected: $TRAVIS_TAG"
    elif [ "$TRAVIS_BRANCH" != "main" ]; then
      echo "Skipping non-main branch build"
      exit 0
    fi
